apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  type: NodePort
  ports:
     - name: http
       nodePort: 30010
       port: 8161
       targetPort: 8161

     - name: endpoint
       nodeport:
       port: 61616

  selector:
    app: queue

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  type: NodePort
  ports:
     - name: http
       nodePort: 30080
       port: 80
  selector:
    app: webapp

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  type: ClusterIP
  ports:
     - name: http
       port: 8080
  selector:
    app: position-tracker

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  type: ClusterIP
  ports:
     - name: http
       port: 8080
  selector:
    app: api-gateway